id: P001660
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:13:06.390654
source_metadata:
  id: bdr:W8870
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན།
  author: ''
  volumes:
    8fe6c50c56e4466ab43fd48904533f25:
      image_group_id: I1706
      title: ''
      volume_number: 1
      total_pages: 608
      base_file: v001.txt
    2cd8890e27094d3ca3360af404777de7:
      image_group_id: I1707
      title: ''
      volume_number: 2
      total_pages: 528
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
