id: ICD2962BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:10:11+00:00'
last_modified: '2022-06-07T13:56:25.774895+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8870
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E505:
      image_group_id: I1706
      title: ''
      total_pages: 608
      order: 1
      base_file: E505.txt
    '0062':
      image_group_id: I1707
      title: ''
      total_pages: 528
      order: 2
      base_file: 0062.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
