id: ICD2962BB
legacy_id: P001660
ocr_import_info:
  bdrc_scan_id: W8870
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:10:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:26:44.317105+00:00'
last_modified: 2022-09-04 11:26:52.054731
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8870
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8870
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན།
  author: སོག་བཟློག་པ་བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9695746791031625
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1706:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1706
      total_pages: 608
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1706.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.974304597410315
    legacy_id: v001
  I1707:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1707
      total_pages: 528
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1707.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.967098660710121
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
